baseurl: /ISPeL-content-machine-learning
title: ISPeL-content-machine-learning
subtitle: Machine Learning.
author: ECU NSF RED Team
simple_search: http://google.com/search
description: ISPeL is an interactive system for personalization of learning. It uses topic-based authoring.
name: ispel-courses
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
port: 7000

